name: ksps_dart
description: Ultra-fast Dart client for ksmux pub/sub system with identical API
version: 1.0.0
homepage: https://github.com/kamalshkeir/thebus

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0